name: Documentation
description: Request changes to documentation.
title: "[Documentation]: "
labels:
  - "documentation"
  - "triage"
body:
  - type: input
    id: summary
    attributes:
      label: Summary of documentation change.
      placeholder: "ex: Include installation in README."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed description of documentation changes.
    validations:
      required: true

  - type: textarea
    id: significance
    attributes:
      label: What gap or improvement will this documentation change serve?
    validations:
      required: true
